# Generated by Django 4.2.3 on 2023-08-06 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_owner_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('store_name', models.CharField(max_length=255)),
                ('store_logo', models.ImageField(upload_to='store_logo/')),
                ('store_tagline', models.CharField(max_length=255)),
                ('store_about_us', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(upload_to='category_store/')),
                ('category_description', models.TextField()),
                ('category_name_of_products', models.IntegerField(default=0)),
                ('category_status', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('product_primary_image', models.ImageField(upload_to='product_imgages/')),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField()),
                ('product_stock', models.BooleanField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.store')),
            ],
        ),
    ]
